<?php

namespace Platform\RestBundle\Entity;

/**
 * RefreshTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefreshTokenRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return RefreshToken[]
     */
    public function getExpiredTokens()
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('e')
            ->from($this->_entityName, 'e')
            ->where('e.expiresAt < :now')
            ->setParameter('now', time())
            ->getQuery()
            ->getResult();
    }
}
