<?php

namespace Platform\RestBundle\Entity;

/**
 * TwitterTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TwitterTokenRepository extends \Doctrine\ORM\EntityRepository
{
}
