<?php

namespace Platform\RestBundle\Entity;

/**
 * ViewsCountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViewsCountRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $type
     * @param integer $id
     * @return integer
     */
    public function getViewsCount($type, $id)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('COUNT(vc)')
            ->from('PlatformRestBundle:ViewsCount', 'vc')
            ->where('vc.type = :type')
            ->andWhere('vc.contentId = :id')
            ->setParameter('type', $type)
            ->setParameter('id', $id)
            ->getQuery()
            ->getSingleScalarResult();
    }

    /**
     * @return array
     */
    public function getTypes()
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('DISTINCT(vc.type) as type')
            ->from('PlatformRestBundle:ViewsCount', 'vc')
            ->getQuery()
            ->getResult();
    }
}
