services:
    pagination.service:
        class: 'Platform\RestBundle\Services\PaginationService'
        arguments: ['@service_container', '@doctrine.orm.entity_manager']
    error.service:
        class: 'Platform\RestBundle\Services\ErrorService'
        arguments: ['@service_container', '@doctrine.orm.entity_manager']
    parameter.service:
        class: 'Platform\RestBundle\Services\ParameterService'
        arguments: ['@service_container', '@doctrine.orm.entity_manager']
    hydration.service:
        class: 'Platform\RestBundle\Services\HydrationService'
        arguments: ['@service_container', '@doctrine.orm.entity_manager']

    rest_exception.listener:
        class: 'Platform\RestBundle\EventListener\ExceptionListener'
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 5000 }
