<?php

namespace Test\MediaBundle\Entity;

/**
 * ImageTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageTagRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Image $entity
     * @param array $ids
     * @return ImageTag[]
     */
    public function getByImageAndTagIDs(Image $entity, $ids = [])
    {
        if (empty($ids))
        {
            return [];
        }

        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('e')
            ->from($this->_entityName, 'e')
            ->where('e.image = :entity')
            ->andWhere('e.tag IN (:ids)')
            ->setParameter('entity', $entity)
            ->setParameter('ids', $ids)
            ->getQuery()
            ->getResult();
    }

    /**
     * @param Tag $entity
     * @param array $ids
     * @return ImageTag[]
     */
    public function getByTagAndImageIDs(Tag $entity, $ids = [])
    {
        if (empty($ids))
        {
            return [];
        }

        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('e')
            ->from($this->_entityName, 'e')
            ->where('e.tag = :entity')
            ->andWhere('e.image IN (:ids)')
            ->setParameter('entity', $entity)
            ->setParameter('ids', $ids)
            ->getQuery()
            ->getResult();
    }
}
